### ISSUE TITLE
Feature Request: Sound on Silent

### ISSUE THREAD

**Issue by Serpensin** [gotify/android#285] opened 2023-04-01 22:48 UTC
I would like the option to enable playing sound even if the phone is set to silent.
I would need this for critical services that need immediate attention.

**Comment by jmattheis** [comment] 2023-04-02 07:50
If you're talking about the do not disturb mode, then you can bypass this by enabling the last setting in the notification settings https://user-images.githubusercontent.com/14895212/156935532-89772e8d-8828-4163-808a-93ce28858622.png

Can we close this as duplicate of https://github.com/gotify/android/issues/203 they are fixing the same use-case I guess?

**Comment by Serpensin** [comment] 2023-04-02 11:13
I know that you can bypass DND.
But if I accidentally turn off the sound, I don't get a notification anymore.

**Closed** 2023-04-03 16:58 UTC
Labels: duplicate
