### ISSUE TITLE
Disable auto scroll in the logs viewer

### ISSUE THREAD

**Issue by ngosang** [gotify/android#165] opened 2021-04-07 07:19 UTC
Gotify/Android 2.1.0

Steps to reproduce:
* Open the log viewer
* Scroll down
* After a few seconds the scroll moves to the top and I can't read the messages

**Comment by jmattheis** [comment] 2021-04-07 17:38
The log view refreshes every x seconds, this probably resets the scroll position. I'd be happy to accept a PR for this improvement.

**Comment by mstuteja** [comment] 2021-08-24 20:47
I'd like to work on this.

**Comment by jmattheis** [comment] 2021-08-25 06:22
@mstuteja :+1:

**Comment by cyb3rko** [comment] 2023-02-08 21:52
Can't reproduce this bug in Version 2.5.1.  
Even when new log entries appear, the scroll position does not change?

Any other opinions?

**Comment by cyb3rko** [comment] 2023-02-09 09:30
Yes, the fix shoudn't be too hard.  
But still I wonder why you encounter these problems while I do not.

I haven't tested it on an Emulator but on my physical phone (ApiVersion 33 as well) everything works fine.  
Nevertheless, fix will come soon.

---

What do you think would be the best solution for that?  
A FloatingActionButton to pause and resume the log updates, an entry in the overflow menu at the top right or something else?

**Comment by jmattheis** [comment] 2023-02-09 09:40
I only can reproduce it on an emulator. But I'm pretty sure that I could reproduce it in the past on my physical device. Maybe it's some weird compatibility layer on the emulator that forces this bug https://stackoverflow.com/a/28306485/4244993

I'd be okay with closing this ticket, as it is apparently fixed on newer, not emulated phones. We could store the scroll position and adjust it accordingly, when the textview is updated.

**Comment by cyb3rko** [comment] 2023-02-09 09:58
Alright, then let's keep it as is.

**Closed** 2023-02-09 10:29 UTC
Labels: a:feature, help wanted, good first issue
