### ISSUE TITLE
Add ability to click on the notification to open url

### ISSUE THREAD

**Issue by Turtvaiz** [gotify/android#66] opened 2019-04-03 15:43 UTC
Example video: https://i.vgy.me/Kfzqx9.mp4

I think this should be fairly easy to implement, but a nice feature to have.

**Comment by eternal-flame-AD** [comment] 2019-04-05 01:48
Sorry but I can't access the video you have sent, but I think this might be a duplicate of https://github.com/gotify/server/issues/65.

**Comment by Turtvaiz** [comment] 2019-04-05 06:48
I don't think it is a duplicate. I only mean supporting launching a browser when tapping on the notification, and I don't think it requires a separate URL parameter as the URL can be parsed from the message content.

I made a wonky patch for myself: Turtvaiz/android@6d55729

**Comment by eternal-flame-AD** [comment] 2019-04-05 08:16
Okay, I got what you meant, but considering we have decided to implement [_actionable notifications_](https://github.com/gotify/server/issues/119) through the newly added "extra" property in the message model in the future, the new mechanism would be able to resolve this problem, so I don't see the particular need for this. I also don't really like searching through the message content and take whatever looks like a URL and use that link as the default behavior for viewing the notification, as makes software behavior rather unpredictable.

@jmattheis what do you think?

**Comment by eternal-flame-AD** [comment] 2019-04-05 08:24
Also, as gotify aims to be both easy to use and understand, please excuse that we usually do not accept feature requests that might in some way confuse other users. However, it is really happy to see that you have came up with your own solution, and we really recommend power users to make modifications to accomodate their own needs.

**Comment by jmattheis** [comment] 2019-04-05 09:07
I also think that this should be done via an extra property. IMO things should be done explicit.

**Closed** 2019-04-08 16:43 UTC

**Comment by mzoeller** [comment] 2020-02-02 08:52
Would you accept a pull request where an extra called "client::click" would be interpreted by the android client?

```
"extras": {
        "client::click": {
            "url": "somescheme://some/link#4"
        }
    }
```

Or is there a better way/more general way to define actionable things?

**Comment by jmattheis** [comment] 2020-02-02 09:23
Hey @mzoeller,

sure thing, pull requests are welcome :D.

But let's define the scheme for the extras, so that is extensible and future proof. In https://github.com/gotify/server/issues/151#issuecomment-473162880 we already have `web::notification` and `android::notification`, so I'd say we use `client::notification` for things that can be supported on both android and web ui.

IMO click should be an object, because in the future there may be something like `javascriptEval` that should be executed on click.

```
{
  "extras": {
    "client::notification": {
      "click": { 
        "url": "https://gotify.net"
      }
    }
  }
}
```

**Comment by mzoeller** [comment] 2020-02-03 15:06
I've submitted a pull request: https://github.com/gotify/android/pull/91
